"""Story S.2 — selector synthesis + quality scoring.

Locks in the AR-7 scoring rubric. These tests are the source of truth
for the editor's selector-picker colour dots. If the rubric changes,
update the doc AND these tests together.
"""

from __future__ import annotations

from src.recording.selector_synthesis import (
    AncestorRef,
    ElementSnapshot,
    synthesise_selectors,
)


def _snap(**kwargs) -> ElementSnapshot:
    kwargs.setdefault("tag", "button")
    kwargs.setdefault("attributes", {})
    return ElementSnapshot(**kwargs)


class TestTestidStrategy:
    def test_stable_testid_wins(self) -> None:
        cands = synthesise_selectors(
            _snap(attributes={"data-testid": "submit-btn"})
        )
        testid = [c for c in cands if c.strategy == "testid"]
        assert len(testid) == 1
        assert testid[0].quality_score == 95
        assert testid[0].value == '[data-testid="submit-btn"]'

    def test_all_configured_attrs_emitted(self) -> None:
        cands = synthesise_selectors(
            _snap(attributes={"data-test-id": "a", "data-qa": "b"})
        )
        emitted = {c.value for c in cands if c.strategy == "testid"}
        assert '[data-test-id="a"]' in emitted
        assert '[data-qa="b"]' in emitted

    def test_autogenerated_hash_testid_is_penalised(self) -> None:
        """20+ chars with mixed case+digits → penalty."""
        cands = synthesise_selectors(
            _snap(attributes={"data-testid": "K8aB9cD1eF2gH3iJ4kL5m"})
        )
        testid = [c for c in cands if c.strategy == "testid"][0]
        assert testid.quality_score == 95 - 25


class TestAriaStrategy:
    def test_role_plus_name_emits(self) -> None:
        cands = synthesise_selectors(
            _snap(aria_role="button", aria_name="Sign in")
        )
        aria = [c for c in cands if c.strategy == "aria"]
        assert len(aria) == 1
        assert aria[0].quality_score == 80

    def test_name_alone_no_role_is_skipped(self) -> None:
        cands = synthesise_selectors(_snap(aria_name="Sign in"))
        aria = [c for c in cands if c.strategy == "aria"]
        assert aria == []

    def test_time_like_name_penalised(self) -> None:
        cands = synthesise_selectors(
            _snap(aria_role="status", aria_name="Updated 12:34")
        )
        aria = [c for c in cands if c.strategy == "aria"][0]
        assert aria.quality_score == 80 - 15


class TestTextStrategy:
    def test_normal_text(self) -> None:
        cands = synthesise_selectors(_snap(text="Sign in"))
        text = [c for c in cands if c.strategy == "text"][0]
        assert text.quality_score == 70

    def test_long_text_penalised(self) -> None:
        cands = synthesise_selectors(
            _snap(text="Lorem ipsum dolor sit amet consectetur adipiscing elit")
        )
        text = [c for c in cands if c.strategy == "text"][0]
        assert text.quality_score == 70 - 20

    def test_numeric_only_heavily_penalised_and_dropped(self) -> None:
        """Numeric-only text: 70 − 30 = 40 — survives the floor but flagged lower."""
        cands = synthesise_selectors(_snap(text="42"))
        text = [c for c in cands if c.strategy == "text"]
        assert text[0].quality_score == 40

    def test_empty_text_no_candidate(self) -> None:
        cands = synthesise_selectors(_snap(text=""))
        assert [c for c in cands if c.strategy == "text"] == []

    def test_text_emits_exact_match_with_quotes(self) -> None:
        """RECORDER-EXACT-TEXT — Playwright's `text="foo"` (with
        quotes) is the EXACT-match form; substring `text=foo` would
        also match a paragraph containing the word, which broke the
        Sourcepoint cookie-banner replay on heise.de."""
        cands = synthesise_selectors(_snap(text="Zustimmen"))
        text_cands = [c for c in cands if c.strategy == "text"]
        assert len(text_cands) == 1
        assert text_cands[0].value == 'text="Zustimmen"'

    def test_text_with_double_quote_skipped(self) -> None:
        """Escaping a literal quote inside the .robot wire format is
        brittle. CSS / testid / aria cover this case; just drop the
        text candidate and let the others carry the test."""
        cands = synthesise_selectors(_snap(text='He said "hi"'))
        assert [c for c in cands if c.strategy == "text"] == []


class TestCssStrategy:
    def test_stable_id_is_emitted(self) -> None:
        cands = synthesise_selectors(_snap(attributes={"id": "login-form"}))
        css = [c for c in cands if c.strategy == "css"]
        assert any(c.value == "#login-form" for c in css)

    def test_autogen_id_dropped(self) -> None:
        cands = synthesise_selectors(
            _snap(attributes={"id": "K8aB9cD1eF2gH3iJ4kL5m"})
        )
        css = [c for c in cands if c.strategy == "css" and c.value.startswith("#")]
        assert css == []

    def test_short_css_in_js_hash_class_dropped(self) -> None:
        """Real heise.de class `jw8mI` (5 chars, letter-digit-letter
        sandwich, no separators) is a CSS-in-JS hash. Old heuristic
        only flagged length>=20; this one catches the short form too."""
        cands = synthesise_selectors(
            _snap(attributes={"class": "jw8mI"})
        )
        # Default _snap tag is "button" → class-based css would be
        # `button.jw8mI`. With the autogen filter it's gone.
        assert not any(
            c.strategy == "css" and "jw8mI" in c.value for c in cands
        )

    def test_emotion_css_hash_class_dropped(self) -> None:
        """Emotion-style `css-1abc23` autogen prefix is a known
        unstable selector. Letter-digit-letter sandwich check catches
        it via the `s-1a` substring."""
        cands = synthesise_selectors(
            _snap(attributes={"class": "css-1abc23"})
        )
        assert not any(
            c.strategy == "css" and "css-1abc23" in c.value for c in cands
        )

    def test_css_modules_hash_suffix_class_dropped(self) -> None:
        """CSS-modules-style `Header__qKw7P` carries a hash suffix
        after `__` — pinned to `_CSS_MODULES_HASH_SUFFIX`."""
        cands = synthesise_selectors(
            _snap(attributes={"class": "Header_link__qKw7P"})
        )
        assert not any(
            c.strategy == "css" and "Header_link__qKw7P" in c.value for c in cands
        )

    def test_human_named_class_with_trailing_digit_kept(self) -> None:
        """Negative case — `btn1`, `step3`, `h2` are human-readable
        names, not hashes. Letter-digit-letter sandwich requires the
        digit to be in the middle of an alphabetic span; trailing
        digits don't trigger."""
        cands = synthesise_selectors(
            _snap(attributes={"class": "btn1 step3"})
        )
        # Default tag is button → expect `button.btn1.step3` to emit.
        css = [c for c in cands if c.strategy == "css" and c.value.startswith("button.")]
        assert css, "human-named classes with trailing digits must NOT be filtered"

    def test_class_selector_penalised_per_extra_class(self) -> None:
        cands = synthesise_selectors(
            _snap(attributes={"class": "btn btn-primary btn-large"})
        )
        css = [c for c in cands if c.strategy == "css" and c.value.startswith("button.")]
        assert css[0].quality_score == 50 - 5 * 2


class TestXpathStrategy:
    def test_absolute_xpath_is_fragile(self) -> None:
        cands = synthesise_selectors(
            _snap(ancestors=[AncestorRef(tag="body"), AncestorRef(tag="div")])
        )
        abs_x = [
            c for c in cands
            if c.strategy == "xpath" and c.value.startswith("/body/div/button")
        ]
        assert abs_x[0].quality_score == 25

    def test_text_anchored_xpath_preferred_over_absolute(self) -> None:
        cands = synthesise_selectors(_snap(text="Sign in"))
        xpath = [c for c in cands if c.strategy == "xpath"]
        scores = sorted(c.quality_score for c in xpath)
        assert 65 in scores  # text-anchored
        assert 25 in scores  # absolute


class TestPlaywrightLocator:
    """`_pw_locator` was removed from `_STRATEGIES` because the
    `getByRole(...)` / `getByText(...)` JS API syntax it produced is
    not valid Browser library selector input. These tests now pin
    the absence of that strategy from synthesis output, and the
    fact that the same elements get covered by `_aria` / `_text`
    in valid Browser library syntax."""

    def test_synthesis_no_longer_emits_pw_locator(self) -> None:
        cands = synthesise_selectors(
            _snap(aria_role="button", aria_name="Save")
        )
        assert all(c.strategy != "pw_locator" for c in cands)

    def test_aria_covers_what_pw_locator_used_to(self) -> None:
        """An element with role + name still produces a candidate via
        `_aria` — in Browser library's `role=...[name="..."]` syntax,
        which IS valid selector input."""
        cands = synthesise_selectors(
            _snap(aria_role="button", aria_name="Save")
        )
        aria = [c for c in cands if c.strategy == "aria"]
        assert aria, "aria strategy should still produce a candidate"
        assert any('role=button' in c.value and 'name="Save"' in c.value for c in aria)


class TestSortOrder:
    def test_highest_quality_first(self) -> None:
        cands = synthesise_selectors(
            _snap(
                attributes={"data-testid": "submit-btn", "class": "btn"},
                aria_role="button", aria_name="Submit", text="Submit",
            )
        )
        # Test-id (95) > aria (80) > text (70) > css (varies).
        # `pw_locator` (was 75) is gone — see TestPlaywrightLocator.
        scores = [c.quality_score for c in cands]
        assert scores == sorted(scores, reverse=True)

    def test_verified_unique_floats_above_higher_quality(self) -> None:
        # Manually construct candidates then re-sort via the same key.
        cands = synthesise_selectors(
            _snap(attributes={"data-testid": "submit"})
        )
        # Flip the testid candidate to verified_unique=True via replacement
        # (SelectorCandidate is frozen — we re-create the list).
        from dataclasses import replace as _r  # noqa: F401
        from src.recording.selector_schema import SelectorCandidate
        idx = next(i for i, c in enumerate(cands) if c.strategy == "testid")
        cands[idx] = SelectorCandidate(
            strategy=cands[idx].strategy,
            value=cands[idx].value,
            quality_score=50,  # lowered ON PURPOSE
            verified_unique=True,
        )
        cands.sort(
            key=lambda c: (c.verified_unique, c.quality_score),
            reverse=True,
        )
        assert cands[0].verified_unique is True


class TestQualityFloor:
    def test_candidates_below_floor_dropped(self) -> None:
        """No strategy for an element with no attributes / text / roles."""
        cands = synthesise_selectors(_snap())
        # With empty inputs only the absolute-xpath path survives.
        assert len(cands) == 1
        assert cands[0].strategy == "xpath"
        assert cands[0].quality_score == 25
