"""Story S.2 — selector synthesis + quality scoring.

Takes an `ElementSnapshot` captured by the Web Recorder's injected
capture script and returns a list of `SelectorCandidate` ordered by
`(verified_unique DESC, quality_score DESC)`.

Quality-score rubric lives in architecture doc AR-7. Keep this file
in sync with the rubric — the scoring numbers here are the source of
truth for the UI colour dots.

Uniqueness verification (S.3) runs elsewhere: this module produces
candidates and scores them, it does NOT touch a live DOM.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from src.recording.selector_schema import SelectorCandidate

# ---------------------------------------------------------------------------
# Input shape
# ---------------------------------------------------------------------------


@dataclass
class AncestorRef:
    """Minimal parent info needed for short-CSS / relative-XPath derivation."""

    tag: str
    attributes: dict[str, str] = field(default_factory=dict)
    nth_of_type: int | None = None  # 1-based among same-tag siblings, or None if unambiguous


@dataclass
class ElementSnapshot:
    """Serialisable DOM element snapshot — injected capture script produces this."""

    tag: str
    attributes: dict[str, str]
    text: str = ""
    aria_role: str | None = None
    aria_name: str | None = None
    ancestors: list[AncestorRef] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Configurable test-id attribute names (matches AR-7)
# ---------------------------------------------------------------------------

TESTID_ATTRS = ("data-test-id", "data-testid", "data-qa", "data-test")

# Heuristic: values that LOOK like hashes / autogenerated class names.
_AUTOGEN_ATTR_VALUE = re.compile(
    r"^[a-zA-Z0-9_-]{20,}$"
    # mix of cases + digits suggests autogen (vs. a human slug like "user-submit-btn")
)


def _looks_autogenerated(value: str) -> bool:
    if len(value) < 20:
        return False
    if not _AUTOGEN_ATTR_VALUE.match(value):
        return False
    has_lower = any(c.islower() for c in value)
    has_upper = any(c.isupper() for c in value)
    has_digit = any(c.isdigit() for c in value)
    # Need at least two of {lower, upper, digit} to flag — a pure lowercase
    # slug like "user-submit-button-primary" would not match.
    return sum([has_lower, has_upper, has_digit]) >= 2


def _cap(score: int) -> int:
    return max(0, min(100, score))


# ---------------------------------------------------------------------------
# Individual strategies
# ---------------------------------------------------------------------------


def _testid(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    for attr in TESTID_ATTRS:
        value = snap.attributes.get(attr)
        if not value:
            continue
        score = 95
        if _looks_autogenerated(value):
            score -= 25
        out.append(
            SelectorCandidate(
                strategy="testid",
                value=f"[{attr}=\"{value}\"]",
                quality_score=_cap(score),
                verified_unique=False,
            )
        )
    return out


def _aria(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    if snap.aria_role and snap.aria_name:
        score = 80
        if re.search(r"\d{2,}|\d{1,2}:\d{2}", snap.aria_name):  # dynamic name (time, counter)
            score -= 15
        out.append(
            SelectorCandidate(
                strategy="aria",
                value=f"role={snap.aria_role}[name=\"{snap.aria_name}\"]",
                quality_score=_cap(score),
                verified_unique=False,
            )
        )
    return out


def _text(snap: ElementSnapshot) -> list[SelectorCandidate]:
    t = snap.text.strip()
    if not t:
        return []
    # RECORDER-EXACT-TEXT — emit Playwright's EXACT-match form
    # (`text="..."` with quotes) instead of the substring form
    # (`text=...`).
    #
    # Why: substring matching catches false positives. Real example
    # from a heise.de Sourcepoint banner: a paragraph reading
    # "Unter Einstellungen können Sie zustimmen..." matched
    # `text=Zustimmen` together with the actual button. With
    # `>> nth=0` disambiguation that would click the paragraph (a
    # no-op or worse) instead of the button. Exact match scopes the
    # locator to elements whose textContent equals the recorded
    # string after trim.
    #
    # Skip when the text contains a literal quote — escaping inside
    # the .robot wire format is brittle and other strategies (CSS,
    # testid, aria) cover those cases. Loss of a text candidate for
    # `He said "hi"` is acceptable.
    if '"' in t:
        return []
    score = 70
    if len(t) > 40:
        score -= 20
    if t.isdigit():
        score -= 30
    return [
        SelectorCandidate(
            strategy="text",
            value=f'text="{t}"',
            quality_score=_cap(score),
            verified_unique=False,
        )
    ]


def _css(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []

    # 1. If we have a stable id, use it.
    el_id = snap.attributes.get("id")
    if el_id and not _looks_autogenerated(el_id):
        out.append(
            SelectorCandidate(
                strategy="css",
                value=f"#{el_id}",
                quality_score=_cap(60),  # not as good as testid but structural
                verified_unique=False,
            )
        )

    # 2. tag + distinctive class combination
    classes = [c for c in snap.attributes.get("class", "").split() if c]
    stable_classes = [c for c in classes if not _looks_autogenerated(c)]
    if stable_classes:
        cls_str = "".join(f".{c}" for c in stable_classes[:3])
        score = 50
        # Each extra class makes the selector more brittle.
        score -= 5 * max(0, len(stable_classes) - 1)
        out.append(
            SelectorCandidate(
                strategy="css",
                value=f"{snap.tag}{cls_str}",
                quality_score=_cap(score),
                verified_unique=False,
            )
        )

    return out


def _xpath(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    t = snap.text.strip()

    # Text-anchored XPath — most stable of the XPath family when text is meaningful.
    if t and len(t) <= 40 and not t.isdigit():
        out.append(
            SelectorCandidate(
                strategy="xpath",
                value=f"//{snap.tag}[normalize-space()=\"{t}\"]",
                quality_score=_cap(65),
                verified_unique=False,
            )
        )

    # Relative-anchored — find nearest ancestor with a stable id or testid.
    for anc in reversed(snap.ancestors):
        anc_id = anc.attributes.get("id")
        testid_attr, testid_val = None, None
        for a in TESTID_ATTRS:
            if a in anc.attributes:
                testid_attr, testid_val = a, anc.attributes[a]
                break
        if anc_id and not _looks_autogenerated(anc_id):
            out.append(
                SelectorCandidate(
                    strategy="xpath",
                    value=f"//*[@id=\"{anc_id}\"]//{snap.tag}",
                    quality_score=_cap(55 - (10 if anc.tag in ("div", "span") else 0)),
                    verified_unique=False,
                )
            )
            break
        if testid_attr and testid_val and not _looks_autogenerated(testid_val):
            out.append(
                SelectorCandidate(
                    strategy="xpath",
                    value=f"//*[@{testid_attr}=\"{testid_val}\"]//{snap.tag}",
                    quality_score=_cap(55),
                    verified_unique=False,
                )
            )
            break

    # Absolute XPath — always fragile, last resort.
    chain = [anc.tag for anc in snap.ancestors] + [snap.tag]
    out.append(
        SelectorCandidate(
            strategy="xpath",
            value="/" + "/".join(chain),
            quality_score=_cap(25),
            verified_unique=False,
        )
    )

    return out


def _pw_locator(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    role = snap.aria_role
    name = snap.aria_name
    if role and name:
        score = 75
        if role in ("group", "generic", "region"):
            score -= 10
        out.append(
            SelectorCandidate(
                strategy="pw_locator",
                value=f'getByRole("{role}", {{ name: "{name}" }})',
                quality_score=_cap(score),
                verified_unique=False,
            )
        )
    # getByText fallback for elements without a role.
    t = snap.text.strip()
    if not role and t and len(t) <= 40:
        out.append(
            SelectorCandidate(
                strategy="pw_locator",
                value=f'getByText("{t}", {{ exact: true }})',
                quality_score=_cap(70),
                verified_unique=False,
            )
        )
    return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


_STRATEGIES = (_testid, _aria, _text, _css, _xpath, _pw_locator)

# Candidates with score below this are dropped — they're worse than having
# no candidate at all (misleads the user into trusting a fragile selector).
_QUALITY_FLOOR = 20


def synthesise_selectors(snap: ElementSnapshot) -> list[SelectorCandidate]:
    """Return selector candidates for the captured element, quality-sorted.

    Candidates below the quality floor are dropped. Sort order matches the
    editor UI's picker: verified_unique first (S.3 will populate this),
    then quality_score descending.
    """
    all_candidates: list[SelectorCandidate] = []
    for strategy_fn in _STRATEGIES:
        try:
            all_candidates.extend(strategy_fn(snap))
        except Exception:
            # A single broken strategy must not lose the others.
            continue

    filtered = [c for c in all_candidates if c.quality_score >= _QUALITY_FLOOR]
    filtered.sort(
        key=lambda c: (c.verified_unique, c.quality_score),
        reverse=True,
    )
    return filtered
