"""Story S.2 — selector synthesis + quality scoring.

Takes an `ElementSnapshot` captured by the Web Recorder's injected
capture script and returns a list of `SelectorCandidate` ordered by
`(verified_unique DESC, quality_score DESC)`.

Quality-score rubric lives in architecture doc AR-7. Keep this file
in sync with the rubric — the scoring numbers here are the source of
truth for the UI colour dots.

Uniqueness verification (S.3) runs elsewhere: this module produces
candidates and scores them, it does NOT touch a live DOM.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from src.recording.selector_schema import SelectorCandidate

# ---------------------------------------------------------------------------
# Input shape
# ---------------------------------------------------------------------------


@dataclass
class AncestorRef:
    """Minimal parent info needed for short-CSS / relative-XPath derivation."""

    tag: str
    attributes: dict[str, str] = field(default_factory=dict)
    nth_of_type: int | None = None  # 1-based among same-tag siblings, or None if unambiguous
    # SHADOW-DOM — set by the capture script when the ancestor's
    # shadowRoot contains (or transitively contains) the captured
    # element. Used by `_pw_locator` to chain a `>>` across the
    # boundary so the resulting selector pierces shadow DOM
    # explicitly rather than relying on Playwright's implicit
    # piercing (which is per-engine and easy to misconfigure).
    is_shadow_host: bool = False


@dataclass
class ElementSnapshot:
    """Serialisable DOM element snapshot — injected capture script produces this."""

    tag: str
    attributes: dict[str, str]
    text: str = ""
    aria_role: str | None = None
    aria_name: str | None = None
    ancestors: list[AncestorRef] = field(default_factory=list)
    # SHADOW-DOM — true iff the captured element lives inside one or
    # more open shadow roots. Synthesis uses it to bias toward
    # pierce-friendly strategies (testid / aria-label / role) over
    # raw CSS class chains, since raw CSS only pierces shadows
    # implicitly when Playwright's CSS engine is the resolver — a
    # Robot Framework run without that explicit engine would miss
    # the element.
    in_shadow_dom: bool = False


# ---------------------------------------------------------------------------
# Configurable test-id attribute names (matches AR-7)
# ---------------------------------------------------------------------------

TESTID_ATTRS = ("data-test-id", "data-testid", "data-qa", "data-test")

# Heuristic: values that LOOK like hashes / autogenerated class names.
_AUTOGEN_ATTR_VALUE = re.compile(
    r"^[a-zA-Z0-9_-]{20,}$"
    # mix of cases + digits suggests autogen (vs. a human slug like "user-submit-btn")
)
# Modern CSS-in-JS (Emotion, Linaria, styled-components) and CSS modules
# emit SHORT hash-y classes that the old length>=20 check missed entirely.
# Two patterns we can spot reliably:
#   1. Letter-digit-letter sandwich (e.g. `jw8mI` from heise.de): natural
#      class names like `btn1` / `h2` have digits at edges, not middle.
#   2. Underscore + alphanumeric segment (CSS modules `__abc123`).
_HASH_DIGIT_IN_MIDDLE = re.compile(r"[a-zA-Z][0-9][a-zA-Z]")
_CSS_MODULES_HASH_SUFFIX = re.compile(r"__[a-zA-Z0-9]{4,}$")
# Emotion-style auto-generated class — `css-1abc23`, `css-h7Sjk2`.
# Anchored prefix + alphanumeric body containing at least one digit
# rules out human classes like `css-utils` or `css-loader`.
_EMOTION_PREFIX = re.compile(r"^css-[a-zA-Z0-9]*[0-9][a-zA-Z0-9]*$")


def _looks_autogenerated(value: str) -> bool:
    if not value:
        return False
    # Long + alphanumeric mix → classic autogen (UUIDs, base32 hashes,
    # webpack-style chunkhashes).
    if len(value) >= 20 and _AUTOGEN_ATTR_VALUE.match(value):
        has_lower = any(c.islower() for c in value)
        has_upper = any(c.isupper() for c in value)
        has_digit = any(c.isdigit() for c in value)
        # Need at least two of {lower, upper, digit} — a pure lowercase
        # slug like "user-submit-button-primary" would not match.
        return sum([has_lower, has_upper, has_digit]) >= 2
    # Short + digit-in-middle of an alphabetic span → CSS-in-JS hash
    # (Emotion `css-1abc23`, generated module class `jw8mI`). The
    # letter-digit-letter sandwich filters out human-named classes
    # like `btn1`, `h2`, `step3` where digits sit at the end.
    if 4 <= len(value) <= 19 and _HASH_DIGIT_IN_MIDDLE.search(value):
        # And require the value to be pure alphanumeric (or with
        # `_`/`-`) — text like `Build #42 done` shouldn't match even
        # though it has a letter-digit-letter sandwich.
        if _AUTOGEN_ATTR_VALUE.fullmatch(value.replace("__", "_")) or re.fullmatch(
            r"[a-zA-Z0-9_-]+", value
        ):
            return True
    # CSS-modules-style hash suffix: `Component__abc123` or
    # `Header_link__qKw7P`.
    if _CSS_MODULES_HASH_SUFFIX.search(value):
        return True
    # Emotion `css-<hash>` — needs explicit handling because the hash
    # part often has digits at the END only, which the
    # letter-digit-letter sandwich check misses.
    if _EMOTION_PREFIX.match(value):
        return True
    return False


def _cap(score: int) -> int:
    return max(0, min(100, score))


# ---------------------------------------------------------------------------
# Individual strategies
# ---------------------------------------------------------------------------


def _testid(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    for attr in TESTID_ATTRS:
        value = snap.attributes.get(attr)
        if not value:
            continue
        score = 95
        if _looks_autogenerated(value):
            score -= 25
        out.append(
            SelectorCandidate(
                strategy="testid",
                value=f"[{attr}=\"{value}\"]",
                quality_score=_cap(score),
                verified_unique=False,
            )
        )
    return out


def _aria(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    if snap.aria_role and snap.aria_name:
        score = 80
        if re.search(r"\d{2,}|\d{1,2}:\d{2}", snap.aria_name):  # dynamic name (time, counter)
            score -= 15
        out.append(
            SelectorCandidate(
                strategy="aria",
                value=f"role={snap.aria_role}[name=\"{snap.aria_name}\"]",
                quality_score=_cap(score),
                verified_unique=False,
            )
        )
    return out


def _text(snap: ElementSnapshot) -> list[SelectorCandidate]:
    t = snap.text.strip()
    if not t:
        return []
    # RECORDER-EXACT-TEXT — emit Playwright's EXACT-match form
    # (`text="..."` with quotes) instead of the substring form
    # (`text=...`).
    #
    # Why: substring matching catches false positives. Real example
    # from a heise.de Sourcepoint banner: a paragraph reading
    # "Unter Einstellungen können Sie zustimmen..." matched
    # `text=Zustimmen` together with the actual button. With
    # `>> nth=0` disambiguation that would click the paragraph (a
    # no-op or worse) instead of the button. Exact match scopes the
    # locator to elements whose textContent equals the recorded
    # string after trim.
    #
    # Skip when the text contains a literal quote — escaping inside
    # the .robot wire format is brittle and other strategies (CSS,
    # testid, aria) cover those cases. Loss of a text candidate for
    # `He said "hi"` is acceptable.
    if '"' in t:
        return []
    score = 70
    if len(t) > 40:
        score -= 20
    if t.isdigit():
        score -= 30
    return [
        SelectorCandidate(
            strategy="text",
            value=f'text="{t}"',
            quality_score=_cap(score),
            verified_unique=False,
        )
    ]


def _css(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []

    # 1. If we have a stable id, use it.
    el_id = snap.attributes.get("id")
    if el_id and not _looks_autogenerated(el_id):
        out.append(
            SelectorCandidate(
                strategy="css",
                value=f"#{el_id}",
                quality_score=_cap(60),  # not as good as testid but structural
                verified_unique=False,
            )
        )

    # 2. tag + distinctive class combination
    classes = [c for c in snap.attributes.get("class", "").split() if c]
    stable_classes = [c for c in classes if not _looks_autogenerated(c)]
    if stable_classes:
        cls_str = "".join(f".{c}" for c in stable_classes[:3])
        score = 50
        # Each extra class makes the selector more brittle.
        score -= 5 * max(0, len(stable_classes) - 1)
        out.append(
            SelectorCandidate(
                strategy="css",
                value=f"{snap.tag}{cls_str}",
                quality_score=_cap(score),
                verified_unique=False,
            )
        )

        # 3. Parent-context disambiguation — `<ancestor#id> <tag.class>`
        #    or `<ancestor[testid=…]> <tag.class>`. Strict-mode
        #    failures at replay come almost entirely from a bare
        #    `tag.class` matching multiple buttons / links across the
        #    page; pinning the nearest stable-id ancestor cuts those
        #    misfires by orders of magnitude. We emit one parent-
        #    scoped variant per stable ancestor we find (first hit
        #    wins among id → testid).
        for anc in reversed(snap.ancestors):
            anc_id = anc.attributes.get("id")
            anc_testid_val: str | None = None
            for a in TESTID_ATTRS:
                v = anc.attributes.get(a)
                if v and not _looks_autogenerated(v):
                    anc_testid_val = (a, v)  # type: ignore[assignment]
                    break
            if anc_id and not _looks_autogenerated(anc_id):
                out.append(
                    SelectorCandidate(
                        strategy="css",
                        value=f"#{anc_id} {snap.tag}{cls_str}",
                        # Higher than the bare tag.class because
                        # parent context is the cheapest unambiguity.
                        quality_score=_cap(score + 10),
                        verified_unique=False,
                    )
                )
                break
            if anc_testid_val:
                attr_name, attr_value = anc_testid_val  # type: ignore[misc]
                out.append(
                    SelectorCandidate(
                        strategy="css",
                        value=f"[{attr_name}=\"{attr_value}\"] {snap.tag}{cls_str}",
                        quality_score=_cap(score + 10),
                        verified_unique=False,
                    )
                )
                break

    return out


def _shadow_chain(snap: ElementSnapshot) -> list[SelectorCandidate]:
    """Emit a Playwright-chained selector across shadow boundaries.

    When the captured element lives inside one or more open shadow
    roots, we synthesise a `<host-selector> >> <inner-selector>`
    chain so the resulting locator pierces shadow DOM explicitly
    (Browser library accepts the `>>` syntax verbatim — Playwright
    parses it as Locator.locator chain).

    Fallback path: if no `is_shadow_host` ancestor is marked, return
    no candidates and let the regular CSS / aria / testid layers
    handle it. They DO pierce open shadows by default in Playwright,
    but a bare `text=Submit` against a page with three shadow-DOM
    web components each containing a Submit button still fails
    strict mode — the chained variant grounds the selector to the
    specific host we recorded.
    """
    if not snap.in_shadow_dom:
        return []

    # Find the nearest shadow host ancestor — its tag + a stable
    # attribute (id / testid) becomes the left side of the chain.
    host_selector: str | None = None
    for anc in snap.ancestors:
        if not anc.is_shadow_host:
            continue
        anc_id = anc.attributes.get("id")
        if anc_id and not _looks_autogenerated(anc_id):
            host_selector = f"#{anc_id}"
            break
        for a in TESTID_ATTRS:
            v = anc.attributes.get(a)
            if v and not _looks_autogenerated(v):
                host_selector = f"[{a}=\"{v}\"]"
                break
        if host_selector:
            break
        # Even just the tag is better than nothing — biased lower
        # because a bare `tag` for the host can match many components.
        host_selector = anc.tag

    if not host_selector:
        return []

    # Build the right side of the chain: prefer testid → aria-label
    # → tag. The point isn't to be the only match — it's to be the
    # only match WITHIN that shadow root, which is a much weaker
    # constraint and almost always achievable.
    inner: str
    inner_score = 70
    el_testid: tuple[str, str] | None = None
    for a in TESTID_ATTRS:
        v = snap.attributes.get(a)
        if v and not _looks_autogenerated(v):
            el_testid = (a, v)
            break
    if el_testid:
        attr_name, attr_value = el_testid
        inner = f"[{attr_name}=\"{attr_value}\"]"
        inner_score = 75
    elif snap.aria_name:
        inner = f"[aria-label=\"{snap.aria_name}\"]"
        inner_score = 65
    else:
        el_id = snap.attributes.get("id")
        if el_id and not _looks_autogenerated(el_id):
            inner = f"#{el_id}"
            inner_score = 60
        else:
            inner = snap.tag
            inner_score = 35  # last resort — weak

    return [
        SelectorCandidate(
            strategy="css",
            value=f"{host_selector} >> {inner}",
            # Bias above bare CSS so the shadow-aware selector wins
            # the tie-break when both strategies produce a candidate.
            quality_score=_cap(inner_score + 5),
            verified_unique=False,
        )
    ]


def _xpath(snap: ElementSnapshot) -> list[SelectorCandidate]:
    out: list[SelectorCandidate] = []
    t = snap.text.strip()

    # Text-anchored XPath — most stable of the XPath family when text is meaningful.
    if t and len(t) <= 40 and not t.isdigit():
        out.append(
            SelectorCandidate(
                strategy="xpath",
                value=f"//{snap.tag}[normalize-space()=\"{t}\"]",
                quality_score=_cap(65),
                verified_unique=False,
            )
        )

    # Relative-anchored — find nearest ancestor with a stable id or testid.
    for anc in reversed(snap.ancestors):
        anc_id = anc.attributes.get("id")
        testid_attr, testid_val = None, None
        for a in TESTID_ATTRS:
            if a in anc.attributes:
                testid_attr, testid_val = a, anc.attributes[a]
                break
        if anc_id and not _looks_autogenerated(anc_id):
            out.append(
                SelectorCandidate(
                    strategy="xpath",
                    value=f"//*[@id=\"{anc_id}\"]//{snap.tag}",
                    quality_score=_cap(55 - (10 if anc.tag in ("div", "span") else 0)),
                    verified_unique=False,
                )
            )
            break
        if testid_attr and testid_val and not _looks_autogenerated(testid_val):
            out.append(
                SelectorCandidate(
                    strategy="xpath",
                    value=f"//*[@{testid_attr}=\"{testid_val}\"]//{snap.tag}",
                    quality_score=_cap(55),
                    verified_unique=False,
                )
            )
            break

    # Absolute XPath — always fragile, last resort. Use the `//`
    # descendant-or-self prefix instead of single `/`: Playwright /
    # Browser library auto-detect a selector as XPath only when it
    # starts with `//` or `..`. A bare `/html/body/...` is parsed as
    # CSS by the engine and never resolves, so the candidate would
    # leak through verification with 0 matches and get dropped — the
    # user would then see ZERO XPath candidates in the picker even
    # for elements that have no other distinguishable attributes.
    # `//html/body/...` matches the same single element (there's only
    # one `<html>` per document) and survives auto-detection.
    chain = [anc.tag for anc in snap.ancestors] + [snap.tag]
    out.append(
        SelectorCandidate(
            strategy="xpath",
            value="//" + "/".join(chain),
            quality_score=_cap(25),
            verified_unique=False,
        )
    )

    return out


def _pw_locator(snap: ElementSnapshot) -> list[SelectorCandidate]:
    """DEPRECATED — produced Playwright JS API syntax (`getByRole(...)`,
    `getByText(...)`) which Browser library cannot parse as a selector
    string. Verify always dropped these candidates as 0-match in
    production, but in unit tests / no-Browser paths a `pw_locator`
    candidate (quality 70-75) could outscore the `_css` one (~55) and
    ship a broken selector into the `.robot`. The functionality is
    fully covered by `_aria` (emits `role=button[name="Submit"]`) and
    `_text` (emits `text="Submit"`), both in valid Browser library
    syntax. Removed from `_STRATEGIES` so it never runs.

    The function body is kept verbatim and the `pw_locator` strategy
    literal still lives in `selector_schema.SelectorStrategy` so
    sidecars saved before this change continue to load. The
    nth-match disambiguation in `selector_verification.py` also
    stays for the same back-compat reason — neither path produces
    new candidates, but loading historical ones must not fail.
    """
    out: list[SelectorCandidate] = []
    role = snap.aria_role
    name = snap.aria_name
    if role and name:
        score = 75
        if role in ("group", "generic", "region"):
            score -= 10
        out.append(
            SelectorCandidate(
                strategy="pw_locator",
                value=f'getByRole("{role}", {{ name: "{name}" }})',
                quality_score=_cap(score),
                verified_unique=False,
            )
        )
    # getByText fallback for elements without a role.
    t = snap.text.strip()
    if not role and t and len(t) <= 40:
        out.append(
            SelectorCandidate(
                strategy="pw_locator",
                value=f'getByText("{t}", {{ exact: true }})',
                quality_score=_cap(70),
                verified_unique=False,
            )
        )
    return out


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


# `_pw_locator` deliberately removed — see its docstring. `_aria` and
# `_text` already cover the same elements in valid Browser library
# syntax; keeping `_pw_locator` here shipped a footgun in test paths
# where the verify pass was skipped.
_STRATEGIES = (_testid, _aria, _text, _css, _shadow_chain, _xpath)

# Candidates with score below this are dropped — they're worse than having
# no candidate at all (misleads the user into trusting a fragile selector).
_QUALITY_FLOOR = 20


def synthesise_selectors(snap: ElementSnapshot) -> list[SelectorCandidate]:
    """Return selector candidates for the captured element, quality-sorted.

    Candidates below the quality floor are dropped. Sort order matches the
    editor UI's picker: verified_unique first (S.3 will populate this),
    then quality_score descending.
    """
    all_candidates: list[SelectorCandidate] = []
    for strategy_fn in _STRATEGIES:
        try:
            all_candidates.extend(strategy_fn(snap))
        except Exception:
            # A single broken strategy must not lose the others.
            continue

    filtered = [c for c in all_candidates if c.quality_score >= _QUALITY_FLOOR]
    filtered.sort(
        key=lambda c: (c.verified_unique, c.quality_score),
        reverse=True,
    )
    return filtered
