"""add docker_build_status and docker_build_error to environments

Revision ID: 9bf996e4380f
Revises: 52b0837c0b7f
Create Date: 2026-03-12 19:09:21.463720
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf996e4380f'
down_revision: Union[str, None] = '52b0837c0b7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_jobs')
    op.drop_table('ai_providers')
    with op.batch_alter_table('environment_packages', schema=None) as batch_op:
        batch_op.alter_column('install_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'installed'"))

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docker_build_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('docker_build_error', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_column('docker_build_error')
        batch_op.drop_column('docker_build_status')

    with op.batch_alter_table('environment_packages', schema=None) as batch_op:
        batch_op.alter_column('install_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'installed'"))

    op.create_table('ai_providers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('provider_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('api_base_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('api_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('temperature', sa.FLOAT(), nullable=False),
    sa.Column('max_tokens', sa.INTEGER(), nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ai_providers_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_ai_providers_name'))
    )
    op.create_table('ai_jobs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('repository_id', sa.INTEGER(), nullable=False),
    sa.Column('provider_id', sa.INTEGER(), nullable=False),
    sa.Column('report_id', sa.INTEGER(), nullable=True),
    sa.Column('spec_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('target_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('result_preview', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('token_usage', sa.INTEGER(), nullable=True),
    sa.Column('triggered_by', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ai_providers.id'], name=op.f('fk_ai_jobs_provider_id_ai_providers')),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_ai_jobs_report_id_reports')),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], name=op.f('fk_ai_jobs_repository_id_repositories')),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], name=op.f('fk_ai_jobs_triggered_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_jobs'))
    )
    # ### end Alembic commands ###
