"""Generate IdP admin handoff artifacts (PDF + Markdown) for customer-org IdP administrators."""

from __future__ import annotations

from io import BytesIO
from typing import TypedDict

from reportlab.graphics.shapes import Drawing, Line, PolyLine, Rect, String
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    Flowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from src.auth.models import IdentityProvider


# ---------------------------------------------------------------------------
# Locale data
# ---------------------------------------------------------------------------


class HandoffLocale(TypedDict):
    title: str
    intro: str
    callback_url_label: str
    callback_url_note: str
    scopes_label: str
    group_claim_label: str
    group_naming_label: str
    group_naming_text: str
    test_login_label: str
    test_login_steps: list[str]
    provider_types: dict[str, str]
    oidc_flow_title: str
    footer: str


_LOCALES: dict[str, HandoffLocale] = {
    "en": HandoffLocale(
        title="IdP Configuration Handoff — RoboScope",
        intro=(
            "This document contains everything your Identity Provider administrator needs "
            "to complete the IdP-side configuration for RoboScope SSO."
        ),
        callback_url_label="Callback URL (Redirect URI)",
        callback_url_note="Register this exact URL as an allowed redirect URI in your IdP application.",
        scopes_label="Required OIDC Scopes",
        group_claim_label="Group Claim Name",
        group_naming_label="Recommended Group Naming Conventions",
        group_naming_text=(
            "Use lowercase, hyphen-separated names (e.g. 'roboscope-admins', 'roboscope-runners'). "
            "Avoid spaces and special characters. Group names are case-sensitive. "
            "Create at least one group and assign your test user to it before running the dry-run."
        ),
        test_login_label="Test-Login Procedure",
        test_login_steps=[
            "Open your IdP's developer console or test tool.",
            "Initiate an authorization request with the client_id configured in RoboScope.",
            "Use redirect_uri exactly as shown in the Callback URL section above.",
            "Request scopes: openid profile email (and your group-claim scope if separate).",
            "Authenticate with a test user that belongs to at least one group.",
            "Inspect the returned id_token claims — confirm the group claim name matches the value above.",
            "Verify the id_token audience (aud) matches the client_id.",
        ],
        provider_types={
            "oidc_azure_ad": "Microsoft Azure Active Directory (Entra ID) — OIDC v2.0 endpoint",
            "oidc_google": "Google Workspace / Google Identity Platform",
            "oidc_github": "GitHub OAuth Apps / GitHub Apps with OIDC",
            "oidc_generic": "Generic OIDC-compliant Identity Provider",
        },
        oidc_flow_title="OIDC Authorization Code Flow Overview",
        footer="Generated by RoboScope. Distribute to your IdP administrator only.",
    ),
    "de": HandoffLocale(
        title="IdP-Konfiguration Handoff \u2014 RoboScope",
        intro=(
            "Dieses Dokument enth\u00e4lt alle Informationen, die Ihr Identity-Provider-Administrator "
            "ben\u00f6tigt, um die IdP-seitige Konfiguration f\u00fcr RoboScope SSO abzuschlie\u00dfen."
        ),
        callback_url_label="Callback-URL (Redirect-URI)",
        callback_url_note=(
            "Registrieren Sie diese genaue URL als erlaubte Redirect-URI in Ihrer IdP-Anwendung."
        ),
        scopes_label="Erforderliche OIDC-Scopes",
        group_claim_label="Gruppen-Claim-Name",
        group_naming_label="Empfehlungen zur Gruppenbenennungskonvention",
        group_naming_text=(
            "Verwenden Sie Kleinbuchstaben mit Bindestrichen (z.\u00a0B. 'roboscope-admins', 'roboscope-runner'). "
            "Vermeiden Sie Leerzeichen und Sonderzeichen. Gruppennamen beachten Gro\u00df-/Kleinschreibung. "
            "Erstellen Sie mindestens eine Gruppe und f\u00fcgen Sie Ihren Testnutzer hinzu, "
            "bevor Sie den Dry-Run starten."
        ),
        test_login_label="Test-Login-Verfahren",
        test_login_steps=[
            "\u00d6ffnen Sie die Entwicklerkonsole oder das Testtool Ihres IdP.",
            "Starten Sie eine Autorisierungsanfrage mit der in RoboScope konfigurierten client_id.",
            "Verwenden Sie redirect_uri genau wie im Abschnitt Callback-URL angegeben.",
            "Fordern Sie die Scopes an: openid profile email (und ggf. Ihren Gruppen-Scope).",
            "Authentifizieren Sie sich mit einem Testnutzer, der mindestens einer Gruppe angeh\u00f6rt.",
            "Pr\u00fcfen Sie die Claims im zur\u00fcckgegebenen id_token \u2014 der Gruppen-Claim-Name muss dem obigen Wert entsprechen.",
            "Stellen Sie sicher, dass die id_token-Audience (aud) mit der client_id \u00fcbereinstimmt.",
        ],
        provider_types={
            "oidc_azure_ad": "Microsoft Azure Active Directory (Entra ID) \u2014 OIDC v2.0 Endpoint",
            "oidc_google": "Google Workspace / Google Identity Platform",
            "oidc_github": "GitHub OAuth Apps / GitHub Apps mit OIDC",
            "oidc_generic": "Generischer OIDC-kompatibler Identity Provider",
        },
        oidc_flow_title="\u00dcberblick: OIDC Authorization Code Flow",
        footer="Generiert von RoboScope. Nur an Ihren IdP-Administrator weitergeben.",
    ),
    "fr": HandoffLocale(
        title="Transfert de configuration IdP \u2014 RoboScope",
        intro=(
            "Ce document contient tout ce dont votre administrateur de fournisseur d\u2019identit\u00e9 "
            "a besoin pour finaliser la configuration c\u00f4t\u00e9 IdP pour le SSO RoboScope."
        ),
        callback_url_label="URL de rappel (Redirect URI)",
        callback_url_note=(
            "Enregistrez cette URL exacte comme URI de redirection autoris\u00e9e dans votre application IdP."
        ),
        scopes_label="Scopes OIDC requis",
        group_claim_label="Nom du claim de groupe",
        group_naming_label="Conventions de nommage recommand\u00e9es pour les groupes",
        group_naming_text=(
            "Utilisez des minuscules s\u00e9par\u00e9es par des tirets (ex.\u00a0: 'roboscope-admins', 'roboscope-runners'). "
            "\u00c9vitez les espaces et les caract\u00e8res sp\u00e9ciaux. Les noms de groupes sont sensibles \u00e0 la casse. "
            "Cr\u00e9ez au moins un groupe et ajoutez votre utilisateur test avant d\u2019ex\u00e9cuter le dry-run."
        ),
        test_login_label="Proc\u00e9dure de connexion test",
        test_login_steps=[
            "Ouvrez la console d\u00e9veloppeur ou l\u2019outil de test de votre IdP.",
            "Initiez une demande d\u2019autorisation avec le client_id configur\u00e9 dans RoboScope.",
            "Utilisez redirect_uri exactement comme indiqu\u00e9 dans la section URL de rappel.",
            "Demandez les scopes\u00a0: openid profile email (et votre scope de groupe si s\u00e9par\u00e9).",
            "Authentifiez-vous avec un utilisateur test appartenant \u00e0 au moins un groupe.",
            "Inspectez les claims du id_token retourn\u00e9 \u2014 le nom du claim de groupe doit correspondre \u00e0 la valeur ci-dessus.",
            "V\u00e9rifiez que l\u2019audience (aud) du id_token correspond au client_id.",
        ],
        provider_types={
            "oidc_azure_ad": "Microsoft Azure Active Directory (Entra ID) \u2014 endpoint OIDC v2.0",
            "oidc_google": "Google Workspace / Google Identity Platform",
            "oidc_github": "GitHub OAuth Apps / GitHub Apps avec OIDC",
            "oidc_generic": "Fournisseur d\u2019identit\u00e9 OIDC g\u00e9n\u00e9rique",
        },
        oidc_flow_title="Aper\u00e7u du flux OIDC Authorization Code",
        footer="G\u00e9n\u00e9r\u00e9 par RoboScope. \u00c0 distribuer uniquement \u00e0 votre administrateur IdP.",
    ),
    "es": HandoffLocale(
        title="Entrega de configuraci\u00f3n IdP \u2014 RoboScope",
        intro=(
            "Este documento contiene todo lo que el administrador de su proveedor de identidad "
            "necesita para completar la configuraci\u00f3n del lado del IdP para el SSO de RoboScope."
        ),
        callback_url_label="URL de devoluci\u00f3n de llamada (Redirect URI)",
        callback_url_note=(
            "Registre esta URL exacta como URI de redirecci\u00f3n permitida en su aplicaci\u00f3n IdP."
        ),
        scopes_label="Scopes OIDC requeridos",
        group_claim_label="Nombre del claim de grupo",
        group_naming_label="Convenciones de nomenclatura recomendadas para grupos",
        group_naming_text=(
            "Use min\u00fasculas con guiones (p.\u00a0ej. 'roboscope-admins', 'roboscope-runners'). "
            "Evite espacios y caracteres especiales. Los nombres de grupo distinguen may\u00fasculas. "
            "Cree al menos un grupo y asigne su usuario de prueba antes de ejecutar el dry-run."
        ),
        test_login_label="Procedimiento de inicio de sesi\u00f3n de prueba",
        test_login_steps=[
            "Abra la consola de desarrollador o herramienta de prueba de su IdP.",
            "Inicie una solicitud de autorizaci\u00f3n con el client_id configurado en RoboScope.",
            "Use redirect_uri exactamente como se muestra en la secci\u00f3n URL de devoluci\u00f3n de llamada.",
            "Solicite los scopes: openid profile email (y el scope de grupo si es independiente).",
            "Aut\u00eantiquese con un usuario de prueba que pertenezca al menos a un grupo.",
            "Inspeccione los claims del id_token devuelto \u2014 el nombre del claim de grupo debe coincidir con el valor anterior.",
            "Verifique que la audiencia (aud) del id_token coincida con el client_id.",
        ],
        provider_types={
            "oidc_azure_ad": "Microsoft Azure Active Directory (Entra ID) \u2014 endpoint OIDC v2.0",
            "oidc_google": "Google Workspace / Google Identity Platform",
            "oidc_github": "GitHub OAuth Apps / GitHub Apps con OIDC",
            "oidc_generic": "Proveedor de identidad OIDC gen\u00e9rico",
        },
        oidc_flow_title="Resumen del flujo OIDC Authorization Code",
        footer="Generado por RoboScope. Distribuya solo a su administrador IdP.",
    ),
}

_MERMAID_FLOW = """\
sequenceDiagram
    participant U as User
    participant R as RoboScope
    participant I as Identity Provider (IdP)

    U->>R: Click "Sign in with <Provider>"
    R->>I: Authorization Request (client_id, redirect_uri, scopes)
    I-->>U: Login & Consent page
    U->>I: Credentials + Consent
    I-->>R: Authorization Code (callback URL)
    R->>I: Token Exchange (code + client_secret)
    I-->>R: id_token + access_token
    R->>R: Validate id_token, extract groups
    R-->>U: Session cookie + redirect to app
"""


def _get_locale(lang: str) -> HandoffLocale:
    return _LOCALES.get(lang, _LOCALES["en"])


def _callback_url(base_url: str) -> str:
    """Build callback URL from the request base_url (includes trailing slash)."""
    return f"{base_url.rstrip('/')}/auth/sso/callback"


# ---------------------------------------------------------------------------
# Markdown generator
# ---------------------------------------------------------------------------


def generate_markdown(idp: IdentityProvider, base_url: str, lang: str) -> str:
    loc = _get_locale(lang)
    provider_desc = loc["provider_types"].get(idp.provider_type, idp.provider_type)
    callback = _callback_url(base_url)

    lines: list[str] = [
        f"# {loc['title']}",
        "",
        f"**{provider_desc}**",
        "",
        loc["intro"],
        "",
        "---",
        "",
        f"## {loc['callback_url_label']}",
        "",
        f"```\n{callback}\n```",
        "",
        f"_{loc['callback_url_note']}_",
        "",
        f"## {loc['scopes_label']}",
        "",
        f"```\n{idp.scopes}\n```",
        "",
        f"## {loc['group_claim_label']}",
        "",
        f"```\n{idp.group_claim_name}\n```",
        "",
        f"## {loc['group_naming_label']}",
        "",
        loc["group_naming_text"],
        "",
        f"## {loc['test_login_label']}",
        "",
    ]
    for i, step in enumerate(loc["test_login_steps"], 1):
        lines.append(f"{i}. {step}")

    lines += [
        "",
        "---",
        "",
        f"## {loc['oidc_flow_title']}",
        "",
        "```mermaid",
        _MERMAID_FLOW.strip(),
        "```",
        "",
        "---",
        "",
        f"_{loc['footer']}_",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PDF generator
# ---------------------------------------------------------------------------


class _OidcFlowDiagram(Flowable):
    """Minimal OIDC flow diagram drawn with reportlab primitives."""

    WIDTH = 14 * cm
    HEIGHT = 6 * cm
    ACTORS = ["User", "RoboScope", "IdP"]
    STEPS = [
        ("U", "R", "1. Login click"),
        ("R", "I", "2. Auth request"),
        ("I", "U", "3. Login page"),
        ("U", "I", "4. Credentials"),
        ("I", "R", "5. Auth code"),
        ("R", "I", "6. Token exchange"),
        ("I", "R", "7. id_token"),
        ("R", "U", "8. Session"),
    ]

    def wrap(self, availWidth: float, availHeight: float) -> tuple[float, float]:
        return self.WIDTH, self.HEIGHT

    def draw(self) -> None:
        w, h = self.WIDTH, self.HEIGHT
        col_w = w / 3

        # Actor boxes
        for i, actor in enumerate(self.ACTORS):
            x = i * col_w + col_w / 2
            bw, bh = 2.2 * cm, 0.6 * cm
            self.canv.setFillColor(colors.HexColor("#1A2D50"))
            self.canv.rect(x - bw / 2, h - bh, bw, bh, fill=1, stroke=0)
            self.canv.setFillColor(colors.white)
            self.canv.setFont("Helvetica-Bold", 8)
            self.canv.drawCentredString(x, h - bh + 0.15 * cm, actor)

        # Lifelines
        self.canv.setStrokeColor(colors.HexColor("#cccccc"))
        self.canv.setLineWidth(0.5)
        for i in range(3):
            x = i * col_w + col_w / 2
            self.canv.line(x, 0, x, h - 0.6 * cm)

        # Steps
        _col_idx = {"U": 0, "R": 1, "I": 2}
        step_h = (h - 0.6 * cm - 0.2 * cm) / len(self.STEPS)
        self.canv.setFont("Helvetica", 6.5)
        self.canv.setStrokeColor(colors.HexColor("#3B7DD8"))
        self.canv.setFillColor(colors.HexColor("#333333"))
        for idx, (src, dst, label) in enumerate(self.STEPS):
            y = h - 0.6 * cm - 0.2 * cm - idx * step_h - step_h * 0.7
            x1 = _col_idx[src] * col_w + col_w / 2
            x2 = _col_idx[dst] * col_w + col_w / 2
            # Arrow line
            self.canv.setLineWidth(1)
            self.canv.line(x1, y, x2, y)
            # Arrowhead
            direction = 1 if x2 > x1 else -1
            self.canv.setFillColor(colors.HexColor("#3B7DD8"))
            p = self.canv.beginPath()
            p.moveTo(x2, y)
            p.lineTo(x2 - direction * 6, y + 3)
            p.lineTo(x2 - direction * 6, y - 3)
            p.close()
            self.canv.drawPath(p, fill=1, stroke=0)
            # Label
            mid_x = (x1 + x2) / 2
            self.canv.setFillColor(colors.HexColor("#333333"))
            self.canv.drawCentredString(mid_x, y + 2, label)


def generate_pdf(idp: IdentityProvider, base_url: str, lang: str) -> bytes:
    loc = _get_locale(lang)
    provider_desc = loc["provider_types"].get(idp.provider_type, idp.provider_type)
    callback = _callback_url(base_url)

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "HandoffTitle",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=16,
        textColor=colors.HexColor("#1A2D50"),
        spaceAfter=6,
    )
    h2_style = ParagraphStyle(
        "HandoffH2",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=11,
        textColor=colors.HexColor("#1A2D50"),
        spaceBefore=12,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "HandoffBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=9,
        leading=13,
        spaceAfter=4,
    )
    mono_style = ParagraphStyle(
        "HandoffMono",
        parent=styles["Code"],
        fontName="Courier",
        fontSize=9,
        backColor=colors.HexColor("#f4f4f4"),
        borderColor=colors.HexColor("#cccccc"),
        borderWidth=0.5,
        borderPadding=4,
        spaceAfter=4,
    )
    note_style = ParagraphStyle(
        "HandoffNote",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=8,
        textColor=colors.HexColor("#666666"),
        spaceAfter=6,
    )
    footer_style = ParagraphStyle(
        "HandoffFooter",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=7,
        textColor=colors.HexColor("#999999"),
        spaceBefore=12,
    )

    story: list = [
        Paragraph(loc["title"], title_style),
        Paragraph(f"<b>{provider_desc}</b>", body_style),
        Spacer(1, 0.2 * cm),
        Paragraph(loc["intro"], body_style),
        Spacer(1, 0.3 * cm),
        Paragraph(loc["callback_url_label"], h2_style),
        Paragraph(callback, mono_style),
        Paragraph(loc["callback_url_note"], note_style),
        Paragraph(loc["scopes_label"], h2_style),
        Paragraph(idp.scopes, mono_style),
        Paragraph(loc["group_claim_label"], h2_style),
        Paragraph(idp.group_claim_name, mono_style),
        Paragraph(loc["group_naming_label"], h2_style),
        Paragraph(loc["group_naming_text"], body_style),
        Paragraph(loc["test_login_label"], h2_style),
    ]

    for i, step in enumerate(loc["test_login_steps"], 1):
        story.append(Paragraph(f"{i}.&nbsp;&nbsp;{step}", body_style))

    story += [
        Spacer(1, 0.3 * cm),
        Paragraph(loc["oidc_flow_title"], h2_style),
        Spacer(1, 0.2 * cm),
        _OidcFlowDiagram(),
        Spacer(1, 0.3 * cm),
        Paragraph(loc["footer"], footer_style),
    ]

    doc.build(story)
    return buf.getvalue()
